services:
  mysql:
    image: mysql:9.4
    container_name: fakement-mysql

    restart: unless-stopped

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fakement

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
