import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { formatDateTime } from "@/lib/formatters";
import { ReceiptIcon } from "@phosphor-icons/react";
import { PaymentEventType } from "@/components/payment-event-type";
import { FindAllPaymentEventsRequest } from "@/http/payment-events-http";
import { Button } from "@/components/ui/button";

export function PaymentEventsPage() {
  const { data, isPending, isError, refetch } = FindAllPaymentEventsRequest();

  if (isPending) {
    return <div>Loading...</div>;
  }

  if (isError) {
    return (
      <div className="flex flex-col items-center gap-4 py-10">
        <p className="text-sm text-muted-foreground">
          Failed to load Payment Events.
        </p>

        <Button onClick={() => refetch()}>Try again</Button>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <header className="flex items-start justify-between gap-6">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <ReceiptIcon size={24} className="font-medium" />
            <h1 className="text-xl font-medium tracking-tight">Events</h1>
          </div>
          <p className="text-sm text-muted-foreground">
            The Events section provides a complete history of payment-related
            events generated by your gateway.
          </p>
        </div>
      </header>

      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>ID</TableHead>
            <TableHead className="text-right">Payment ID</TableHead>
            <TableHead className="text-right">Type</TableHead>
            <TableHead className="text-right">Created At</TableHead>
          </TableRow>
        </TableHeader>

        <TableBody>
          {data?.map((item) => (
            <TableRow key={item.id}>
              <TableCell>{item.id}</TableCell>
              <TableCell className="text-right">{item.paymentId}</TableCell>
              <TableCell className="text-right font-mono font-medium">
                <PaymentEventType type={item.type} />
              </TableCell>
              <TableCell className="text-right">
                {formatDateTime(item.createdAt)}
              </TableCell>
            </TableRow>
          ))}

          {data?.length === 0 && (
            <TableRow>
              <TableCell
                colSpan={5}
                className="py-10 text-center text-muted-foreground"
              >
                No Events found.
              </TableCell>
            </TableRow>
          )}
        </TableBody>
      </Table>
    </div>
  );
}
